name: CI-compile

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ps2homebrew/ps2homebrew@sha256:3d3709cc2e72921b5a1892a57797fcedf37d620ab04309a8dc4af77053f8e5df
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - run: |
        cd hddtester
        make

    - name: Upload release artifact ELF
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        path: |
          hddtester/bin/*.elf
