name: CI-compile

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
    - name: git checkout
      uses: actions/checkout@v3

    - run: |
        git clone https://github.com/ps2dev/ps2sdk
        echo "$GITHUB_WORKSPACE/ps2sdk" >> $PS2SDKSRC
        cd hddtester
        make

    - name: Upload release artifact ELF
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        path: |
          hddtester/bin/*.elf
