name: CI-compile

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ps2homebrew/ps2homebrew@sha256:4363345d88606ee2b9e6aebaddef832f68e6ab5a5ceb488fe981d1594f98fb2e
    steps:
    - name: git checkout
      uses: actions/checkout@v4

    - run: |
        cd hddtester
        make

    - name: Upload release artifact ELF
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        path: |
          hddtester/bin/*.elf
